local:
    env_file: .env
    ports:
        postgres: 5433
        webserver: 8888
        redis: 6380
    environment:
        AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8888
        AIRFLOW__API__PORT: 8888
project:
    name: genetl-ai-platform
